apiVersion: v1
kind: Service
metadata:
  name: {{ include "pi.fullname" . }}-api
spec:
  selector:
    {{- include "pi.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - {name: http, port: 8000, targetPort: http}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pi.fullname" . }}-workers
spec:
  clusterIP: None
  selector:
    {{- include "pi.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
  ports:
    - {name: http, port: 8080, targetPort: http}
