name: Quality
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  quality:
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          version: '0.10.9'
          python-version: '3.12'
          enable-cache: true
      - uses: azure/setup-helm@v4.3.0
        with:
          version: v3.17.3
      - run: uv sync --locked
      - run: make check
      - run: make docs-check
      - run: make test-container
      - run: make test-mongodb
